# ==================================================================
#  tubex-lib - travis test script
# ==================================================================

language: c++
sudo: false

addons:
  apt:
    sources:
    - deadsnakes
    - ubuntu-toolchain-r-test
    - chef-current-precise

    packages:
    - cmake
    - time
    - pkg-config
    - g++-5
    - libboost-dev
    #- doxygen # for documentation
    #- graphviz # for documentation

sudo: required

cache:
  directories:
  #- $HOME/ibex

matrix:
  include:
  #- os: osx
  #  compiler: clang
  - os: linux
    compiler: gcc-5

#before_install:
#  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install clang-omp; fi

install:
  - sudo sh ./scripts/ibex/build_IbexLib.sh
  #- sudo sh ./scripts/ibex/build_IbexGeometryLib.sh
  #- sudo pip install breathe # for documentation
  #- export PKG_CONFIG_PATH=$PKG_CONFIG_PATH:$HOME/ibex

script:
  #- mkdir make
  #- cd make
  #- if [ $TRAVIS_OS_NAME == osx ]; then
  #    CC=clang-omp CXX=clang-omp++ cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DBUILD_TESTS=ON ../ ;
  #  fi
  #- if [ $TRAVIS_OS_NAME == linux ]; then
  #    cmake -DCMAKE_INSTALL_PREFIX=${HOME} -DIBEX_ROOT=${HOME}/ibex -DCMAKE_CXX_COMPILER=g++-5 -DBUILD_TESTS=ON ../ ;
  #  fi
  #- make
  - pwd
  - ls
  - ./build.sh all
  - cd make ; make test