on:
    push:
        branches: 'master'
        tags: '' # Restrict to blank tags
    pull_request:

jobs:
 dockercentos:
    name: CentOS Docker
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v2
      with:
        submodules: true
        fetch-depth: 0
        clean: false
    - run: |
        chmod a+x scripts/docker/build_pybinding.sh
        docker run --rm -v `pwd`:/io benensta/pyibex-docker /io/scripts/docker/build_pybinding.sh
        ls wheelhouse
    - uses: xresloader/upload-to-github-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        file: "wheelhouse/*.whl"
        overwrite: true
        tag_name: autotagname-${{ github.sha }}
      if: (github.event_name != 'pull_request')&&(github.ref_name == 'master')
